# Generated by Django 6.0.2 on 2026-08-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='offline', max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
